- name: To install Nginx and start services
  become: yes # -b
  tasks:
  - name: Install
    ansible.builtin.package:
     name: nginx
     state: install
  - name: Service start
    ansible.builtin.service:
     name: nginx
     state: present
 