- name: To install Nginx and start services
  hosts: web
  become: yes # -b
  tasks:
  - name: Install
  # reason why we are using package module even we have dnf module is dnf wont work on Ubuntu here package module is heterogenous
    ansible.builtin.package:
      name: nginx
      state: present
  - name: Service start
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
