- name: To install Nginx and start services
  hosts: web
  become: yes # -b
  tasks:
  - name: Install
    ansible.builtin.package:
      name: nginx
      state: present
  - name: Service start
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
