- name: variables
  hosts: local
  connection: local
  vars: #playbook level variables declare
    course: "Devops with AWS"
    Duration: 120hrs
    Trainer: Sivakumar
  tasks:
  - name: print the variables
    vars: #Task level variables
      course: ansible
    ansible.builtin.debug:
      msg: "Course is {{ course }}, duration {{ Duration }}, trainer is {{ Trainer }}" 

  - name: print the variable
    ansible.builtin.debug:
      msg: "Course is {{ course }}, Duration is {{ Duration }}, trainer is {{ Trainer }}"