- name: Data types in Yaml
  hosts: local
  connections: local
  vars:
    course_name: "Devops with AWS"  #string
    duration: "120" #int
    topics: #list
    - linux
    - shell
    - ansible
    - AWS
    live: true #bollen
    tools:
      ci: jenkins #map
      cloud: AWS
      container: docker
  tasks:
  - name: print details
    ansible.builtin.debug:
      msg: "Hello i am learning {{ course_name }} and duration is {{ duration }}, topics are {{ topics }}, is it {{ live }} and tools covered are {{ tools }} "    