- name: Playbook for data types
  hosts: local
  connection: local
  vars:
   course: "Devops with AWS"
   Duration: 120
   topics:
   - AWS
   - Devops
   - Shell
   - Ansible
   is_live: true
   tools:
     ci: jenkins
     cloud: AWS
     cotainerization: Docker
  tasks:
  - name: data type print
    ansible.builtin.debug:
      msg: "Hello I am learning {{ course }}, and duration is {{ Duration }}, topics covered are {{ topics }}, is it live {{ is_live }} and tools using are {{ tools }}"
    