- name: playbook for conditions
  hosts: local
  connection: local
  vars:
    my_number: 2
  tasks:
  - name: print if the number greater than 10
    ansible.builtin.debug:
      msg: "Given number {{ my_number }} is greater then 12"
    when: my_number > 10

  - name: print if the number less than or equal to 10
    ansible.builtin.debug:
      msg: "Given number {{ my_number }} is less  then 12"
    when: my_number <= 10
