- name: Install/unistall pacakges in loop
  hosts: web
  become: yes
  tasks:
  - name: install in loop
    ansible.builtin.package:
      name: "{{ item }}"
      state: "{{}}"
    loop:
      - { name: 'wget', state: 'absent'}
      - { name: 'git', state: 'absent'}
      - { name: 'gcc', state: 'present'}
      - { name: 'zip', state: 'absent'}
    when: ansible_os_family == "RedHat"
