- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefine variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Ramesh') }}"


  - name: convert string to list
    vars:
      fruits: "apple, banana, orange"
    ansible.builtin.debug:
      msg: "Furits are{{ fruits | split(',')}}"


  - name: convert string to list
    vars:
      course:
        name: Ansbile
        duration: 120
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "Course info: {{ course | dict2items }}"

  - name: convert list into map
    vars:
      course:
        - { key: 'name', value: 'ansible'}
        - { key: 'duration', value: '120'}
        - { key: 'trainer', value: 'sivakumar'}
    ansible.builtin.debug:
      msg: "Course info {{ course | items2dict }}"

  - name:  Convert upper to lower
    vars:
      name: "Sivakumar Readdy M"
    ansible.builtin.debug:
      msg: " Hello {{ name | lower }}"

  - name: Convert lower to Upper
    vars: 
      name: "sivakumar reddy"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"

  - name: Print max and min
    vars:
      numbers: [1,34,56,72,98,4]
    ansible.builtin.debug:
       msg: " Max num is {{ numbers | max }} min number is {{ numbers | min}}"


  - name: check ip address is valid or not
    vars: 
      ip: "54.173.65.102"
    ansible.builtin.debug:
       msg: "{{ ip | ansible.utils.ipaddr }}"             



