- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefine variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Ramesh') }}"


  - name: convert string to list
    vars:
      fruits: "apple, banana, orange"
    ansible.builtin.debug:
      msg: "Furits are{{ fruits | split(',')}}"


  - name: convert string to list
    vars:
      course:
        name: Ansbile
        duration: 120
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "Course info: {{ course | dict2items }}"

  - name: convert list into map
    vars:
      course:
        - { key: 'name', value: 'ansible'}
        - { key: 'duration', value: '120'}
        - { key: 'trainer', value: 'sivakumar'}
    ansible.builtin.debug:
      msg: "Course info {{ course | items2dict }}"

  - name:  Convert to lower
    vars:
      name: "Sivakumar Readdy M"
    ansible.builtin.debug:
      msg: " Hello {{ name | lower }}"    



