- name: shell vs command
  hosts: local
  connection: local
  tasks:
  - name: execute command
    #ansible.builtin.command ls -ltr >/tmp/output
    ansible.builtin.shell: ls -ltr > /tmp/output.txt

  - name: execute  ls in command module
    ansible.builtin.command: ls -ltr
    register: command_result

  - name: print the /tmp/output
    ansible.builtin.debug:
      msg: "{{ command_result}}"  

