- name: Create Ec2 and R53 record from Ansible
  hosts: local
  connection: local

  vars:
    subnet_id: subnet-082c8a70963f4eed4
    sg_id: sg-0ba3f07a1e0cdffa4
    ami_id: ami-09c813fb71547fc4f
    instance_type: t2.micro
    zone: jaydevops.online
    instances:
    - mysql
    - backend
    - frontend
  
  tasks:
  - name: install python libs
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore

  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id  }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instances }}"
    register: ec2_info

  # - name: print ec2_info
  #   ansible.builtin.debug:
  #     msg: "Aws ec2 info {{ ec2_info }}"

  - name: print ec2 instances private IP address
    ansible.builtin.debug:
      msg: "{{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_info.results }}"  

  - name: create private ip r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_info.results }}"

  - name: create public ip for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_info.results }}"
    when: item.item == "frontend"